# fly.toml app configuration file generated for eksiseyler-api on 2024-10-15T23:47:00+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'eksiseyler-api'
primary_region = 'ams'

[build]

[processes]
  web = "fastapi run app/main.py"
  cron = "python /code/etl/scraper.py && supercronic etl/crontab"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['web']

[[vm]]
  size = 'shared-cpu-1x'
