# fly.toml app configuration file generated for eksiseyler-api on 2024-10-15T23:47:00+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'eksiseyler-api'
primary_region = 'ams'

[build]

[processes]
  web = "fastapi run app/main.py"
<<<<<<< HEAD
  cron = "sh -c 'python etl/scraper.py --max-pages 1 && supercronic etl/crontab'" # 'sh -c' is necessary to run multiple commands in a single process
=======
  cron = "sh -c 'python etl/scraper.py --max-pages 0 && supercronic etl/crontab'" # 'sh -c' is necessary to run multiple commands in a single process
>>>>>>> 3ce1e4bb823077d0a4508503bbc90952d58e3408

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['web']

[[vm]]
  size = 'shared-cpu-1x'
